### ISSUE TITLE
table name prefix

### ISSUE THREAD

**Issue by gwmoura** [railsblocks/railsblocks-shop#1]
@fernandes the configurations on `environment.rb` will be replicaded on rails app?

example: we want set table name prefix to all models in one railsblock, putting `config.active_record.table_name_prefix = "prefix_"` in `config/environment.rb`. When we run `rake db:migrate` in a rails app this configuration will be replicated affecting all app or just my railsblocks?

**Comment by fernandes** [comment]
not sure about the `environment.rb`, but I'm pretty sure initializers will run on main app :+1:

**Comment by gwmoura** [comment]
@fernandes today we use modules to set table name prefix.
```ruby
module Shop
  def self.table_name_prefix
    'shop_'
  end
end
```
I don't use RailsBlocks::Shop::Shop::Category and I don't write `table_name_prefix = 'shop_'` in all models for shop.

Sugestions:

* exclude shop module
* set `self.table_name = "shop_[model]"` in all models

I have more options?
